// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsxwzvdluvqfehyoidbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzeHd6dmRsdXZxZmVoeW9pZGJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzcwODksImV4cCI6MjA2NjUxMzA4OX0.bAUYXbnqwT3o9D8xJPJoSqMI92O09mI0LJXwW2IA1Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);